### PR TITLE
original schema

### PR DESCRIPTION
**Pull request by poorvarathore05**

### CODE REVIEW

**Review by montrealist — APPROVED** [review]
I see that these are original files. Can you create a pull request with your changes to these?

**Comment by montrealist** [comment]
Here's how I would do it: https://github.com/montrealist/data-modeling-exercise-example/pull/1/files

The original code is on the left, your solution is on the right. Very easy for me to review. Does it make sense?

**Comment by montrealist** [comment]
Hi Poorva,

Please merge this when ready. Pull requests that are open for too long (more than a few days) risk becoming 'stale': we lose context of the code changes, and sometimes more recent changes to the repository make the previous open pull requests obsolete.

**Comment by poorvarathore05** [comment]
Hello Max,
Sure I will merge it.

**Pull request closed without merging**
